apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::215417967337:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::215417967337:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XQTUAELMLDS0
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-06-30T08:16:03Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '2122'
  uid: 029db269-1c41-49ad-946a-11940e18495f
