apiVersion: v1
data:
  mapRoles: |
    - groups:
          - system:masters
          rolearn: arn:aws:iam::215417967337:role/UdacityFlaskDeployCBKubectlRole
          username: build      
    - groups:
          - system:bootstrappers
          - system:nodesexit
          rolearn: arn:aws:iam::215417967337:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OHNEQ7RK9EW4
          username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-06-29T07:35:02Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1560'
  uid: e14630f3-9571-4574-a791-587362d8aa95
