apiVersion: v1
data:
  mapRoles: "- groups:\n      - system:masters\n      rolearn: arn:aws:iam::215417967337:role/UdacityFlaskDeployCBKubectlRole\n
    \     username: build      \n- groups:\n      - system:bootstrappers\n      -
    system:nodesexit\n      rolearn: arn:aws:iam::215417967337:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-OHNEQ7RK9EW4\n
    \     username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-29T07:35:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "103280"
  uid: e14630f3-9571-4574-a791-587362d8aa95
